--Oracle PL/SQL

SELECT H.HACKER_ID, H.NAME, COUNT(C.HACKER_ID)
FROM HACKERS H
JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(C.CHALLENGE_ID) = (
    SELECT MAX(COUNT(HACKER_ID))
    FROM CHALLENGES
    GROUP BY HACKER_ID
)
OR COUNT(C.CHALLENGE_ID) IN (
    SELECT total_por_hacker  
    FROM (
        SELECT COUNT(challenge_id) AS total_por_hacker 
        FROM CHALLENGES
        GROUP BY hacker_id
    ) sub_tabela
    GROUP BY total_por_hacker 
    HAVING COUNT(*) = 1
)
ORDER BY COUNT(C.HACKER_ID) DESC, H.HACKER_ID;
